#!/bin/sh

set -e
cmd=$1
shift
case "$cmd" in
  get-version)
      head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
    ;;
  build-exclude-list|dist-exclude-list|prepare-dist)
    ;;
  bootstrap)
    echo "bootstrap not needed"
    ;;
  configure)
    if [ "`uname -s`" = "Darwin" ]; then
      if [ -n "$ZBS_ARCH" ] && [ "$ZBS_ARCH" = "i386" ]; then
        target="darwin-i386-cc"
      else
        target="darwin64-x86_64-cc"
      fi
    else
      if [ `uname -m` = "x86_64" ]; then
        target="debug-linux-generic64"
      else
        target="debug-linux-generic32"
      fi
    fi
    ./Configure $target shared no-idea no-mdc2 no-rc5 $@ --openssldir='${prefix}/usr'
    make links
    make depend
    ;;
  make)
    args=""
    for arg in $@; do
        if [ "$arg" = "check" ]; then
            arg=""
        fi
        args="$args $arg"
    done
    make $args
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
