#!/bin/sh

cmd=$1
shift
case "$cmd" in
  bootstrap)
    echo "bootstrap not needed"
    ;;
  configure)
    if [ `uname -m` = "x86_64" ]; then
    	target="debug-linux-generic64"
    else
        target="debug-linux-generic32"
    fi
    ./Configure $target shared no-idea no-mdc2 no-rc5 $@ --openssldir='${prefix}/usr'
    ;;
  make)
    make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0
