#!/bin/sh -e

cmd=$1
shift
case "$cmd" in
  build-exclude-list|dist-exclude-list|prepare-dist)
    ;;
  bootstrap)
    echo "bootstrap not needed"
    ;;
  configure)
    if [ `uname -m` = "x86_64" ]; then
      target="debug-linux-generic64"
    else
      target="debug-linux-generic32"
    fi
    ./Configure $target shared no-idea no-mdc2 no-rc5 $@ --openssldir='${prefix}/usr'
    ;;
  make)
    make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
